stages: 
  - testing
tester_job: 
  allow_failure: true
  artifacts: 
    expire_in: "1 day"
    paths: 
      - ./allure-results
    when: always
  script: 
    - "pytest --alluredir=./allure-results"
  stage: testing
  tags: 
    - tester
